language: c
notifications:
   slack: skydreams:1FLUnEeqaNLinKq1p0lJf9F5
services:
 - docker
env:
 - BASE_IMAGE="dellelce/python-base" TARGET_IMAGE="dellelce/airflow-base" PREFIX="/app/airflow"
script: 
 - ./main.sh
