language: c
notifications:
   slack: skydreams:1FLUnEeqaNLinKq1p0lJf9F5
services:
 - docker
env:
 - BASE_IMAGE="dellelce/py-base" TARGET_IMAGE="dellelce/tf-base" PREFIX="/app/tf"
script: 
 - ./main.sh
